# fly.toml app configuration file generated for onestack-ancient-smoke-257 on 2024-05-20T22:18:52+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'onestack-ancient-smoke-257'
primary_region = 'syd'
kill_signal = 'SIGTERM'

[build]

[env]
DATABASE_PATH = '/mnt/name/prod_20240802.db'
PHX_HOST = 'onestack.cloud'
PORT = '8080'

[[mounts]]
source = 'name'
destination = '/mnt/name'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 1000
soft_limit = 1000

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
