services:
    mongodb:
        image: "mongo:7"
        command: mongod
        container_name: mongodb
        env_file:
            - .env
        restart: unless-stopped
        networks:
            - traefik_default
        labels:
            - "traefik.enable=true"
            - "traefik.tcp.routers.mongodb.rule=HostSNI(`*`)"
            # - "traefik.tcp.routers.postgres.tls=true"
            - "traefik.tcp.routers.mongodb.entrypoints=mongodb"
            # - "traefik.tcp.routers.postgres.tls.certresolver=letsencrypt"
            - "traefik.tcp.services.mongodb.loadbalancer.server.port=27017"
        ports:
            - "27018:27017"
        healthcheck:
            test:
                - CMD
                - echo
                - ok
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 5s
        # mem_limit: "0"
        # memswap_limit: "0"
        # mem_swappiness: 60
        # mem_reservation: "0"
        # cpus: 0.0
        # cpu_shares: 1024
        volumes:
            - "/root/databases/mongodb/data/configdb:/data/configdb"
            - "/root/databases/mongodb/data/db:/data/db"

networks:
    traefik_default:
        external: true
