services:
  app:
    image: linkstackorg/linkstack:latest
    container_name: "linkstack"
    environment:
      TZ: 'Australia/Sydney'
      SERVER_ADMIN: 'george@onestack.cloud'
      HTTP_SERVER_NAME: 'link.onestack.cloud'
      HTTPS_SERVER_NAME: 'link.onestack.cloud'
      LOG_LEVEL: 'info'
      PHP_MEMORY_LIMIT: '256M'
      UPLOAD_MAX_FILESIZE: '8M'
      FORCE_HTTPS: true
    volumes:
      - 'linkstack_data:/htdocs'
    restart: unless-stopped

    networks:
    - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linkstack_linkstack.tls=true"
      - "traefik.http.services.linkstack_linkstack.loadbalancer.server.port=80"
#        - "traefik.http.services.linkstack_linkstack.loadbalancer.scheme=https"
      - "traefik.http.routers.linkstack_linkstack.rule=Host(`link.onestack.cloud`)"
      - "traefik.http.routers.linkstack_linkstack.entrypoints=websecure"
      - "traefik.http.routers.linkstack_linkstack.tls.certresolver=letsencrypt"
      - "traefik.http.routers.linkstack_linkstack.service=linkstack_linkstack"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.linkstack_linkstack-ui.middlewares=linkstack_linkstack-header"
      - "traefik.http.middlewares.linkstack_linkstack-header.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.linkstack_linkstack-header.headers.customResponseHeaders.X-Robots-Tag=none"
      - "traefik.http.middlewares.linkstack_linkstack-header.headers.customResponseHeaders.Strict-Transport-Security=max-age=63072000"
      - "traefik.http.middlewares.linkstack_linkstack-header.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.linkstack_linkstack-header.headers.accesscontrolalloworiginlist=*"

networks:
  traefik_default:
    external: true

volumes:
  linkstack_data: