services:
    matrix_docker:
        container_name: matrix_docker
        image: "matrixconduit/matrix-conduit:latest"
        restart: unless-stopped
        volumes:
            - "/root/matrix_docker/matrix-conduit:/var/lib/matrix-conduit/"
        environment:
            CONDUIT_SERVER_NAME: matrix.${TOP_LEVEL_DOMAIN}
            CONDUIT_DATABASE_PATH: /var/lib/matrix-conduit/
            CONDUIT_PORT: 6167
            CONDUIT_MAX_REQUEST_SIZE: 20000000
            CONDUIT_ALLOW_REGISTRATION: "true"
            CONDUIT_REGISTRATION_TOKEN: ${CONDUIT_REGISTRATION_TOKEN}
            CONDUIT_ALLOW_FEDERATION: "true"
            CONDUIT_ALLOW_CHECK_FOR_UPDATES: "true"
            CONDUIT_TRUSTED_SERVERS: '["matrix.org"]'
            CONDUIT_ADDRESS: 0.0.0.0
            # CONDUIT_CONFIG: ""
            CONDUIT_TURN_URIS: '["turn:${SSH_HOST}:3478?transport=udp", "turn:${SSH_HOST}:3478?transport=tcp"]'
            CONDUIT_TURN_USERNAME: 
            CONDUIT_TURN_PASSWORD: 
            CONDUIT_ENABLE_LIGHTNING_BOLT: false
            CONDUIT_DATABASE_BACKEND: sqlite
        labels:
            - traefik.enable=true
            - traefik.http.routers.matrix.rule=Host(`matrix.${TOP_LEVEL_DOMAIN}`)
            - traefik.http.routers.matrix.tls=true
            - traefik.http.routers.matrix.tls.certresolver=${CERT_RESOLVER:-letsencrypt}
            - traefik.http.services.matrix.loadbalancer.server.port=6167
        networks:
            - traefik_default

networks:
    traefik_default:
        external: true
