services:
  uptime-kuma:
    image: "louislam/uptime-kuma:latest"
    container_name: uptime-kuma
    restart: always

    volumes:
      - ./uptime-kuma-data:/app/data

    networks:
      - traefik_default

    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.uptime-kuma.rule=Host(`kuma.${TOP_LEVEL_DOMAIN}`)"
        - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
        - "traefik.http.routers.uptime-kuma.tls=true"
        - "traefik.http.routers.uptime-kuma.tls.certresolver=${CERT_RESOLVER:-letsencrypt}"
        - "traefik.http.services.uptime-kuma.loadBalancer.server.port=3001"

networks:
  traefik_default:
    external: true