services:
    n8n:
        image: docker.n8n.io/n8nio/n8n
        restart: always
        env_file:
            - .env

        volumes:
            - n8n_storage:/home/node/.n8n
        labels:
            - traefik.enable=true
            - traefik.http.routers.n8n.rule=Host(`n8n.${TOP_LEVEL_DOMAIN}`)
            - traefik.http.routers.n8n.tls=true
            - traefik.http.routers.n8n.tls.certresolver=${CERT_RESOLVER:-letsencrypt}
            - traefik.http.services.n8n.loadbalancer.server.port=5678
        networks:
            - traefik_default

networks:
    traefik_default:
        external: true
volumes:
    n8n_storage:
